defaults:
    - _self_
    - agent: sac

#env
env: dog_stand

# Basic setup
experiment: sac
device: cuda
seed: 1

# training 
num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}
num_seed_steps: 5000
eval_frequency: 10000
num_eval_episodes: 10

# unsupervise
num_unsup_steps: 0
topK: 5
reset_update: 100

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: false
save_model: true

# hydra configuration
hydra:
    run:
        dir: ./exp/${env}/${experiment}_seed${seed}
        
vis_Q: False
is_V_dual: False
num_seed: 12345
log_dir: "default/logs"